version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: taskdef.json
        LoadBalancerInfo:
          ContainerName: "api-container-app"
          ContainerPort: 80
ImageDefinitions: imageDetail.json