version: 0.2
env:
  variables:
    ECR_REPO_NAME: api-repository

phases:
  pre_build:
    commands:
      - echo "hello"
      - echo Logging in to DockerHub...
      # Secrets Managerから安全に取得（標準出力は捨てる）
      - export DOCKERHUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub/credential --query SecretString --output text | jq -r '.username') >/dev/null
      - export DOCKERHUB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub/credential --query SecretString --output text | jq -r '.password') >/dev/null
      # 取得後にdocker login（パスワードは標準入力）
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - echo DockerHub login successful.
      #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .
  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

      #- printf '[{"name":"api-container-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' ${ECR_IMAGE_URI} > imageDetail.json

artifacts:
  files:
#    - imagedefinitions.json
    - appspec.yml
    - taskdef.json
    - imageDetail.json
